### ISSUE TITLE
请教关于点对点部分的问题

### ISSUE THREAD

**Issue by wowzql** [OkamiSupport/How-to-build-your-own-private-network#2]
使用shadowvpn 和其他vpn进行点对点有什么差别么，曾使用openvpn做点对点，但是感觉会被墙屏蔽的很严重，现在用shadowvpn发现带宽有时不够用。。莫名其妙的会不够。。。和  concurrency=1 有关么？数值越大支持带宽越高？会有什么副作用么。。。服务器与服务器链接的部分，可否使用L2TP-ipsec呢，稳定性如何呢~ 求大神可以给详细讲解下，小弟不胜感激

**Comment by littlewolf9527** [comment]
没有遇到过带宽不够的情况，可以用nc压测一下隧道性能。
不够的话可能与服务器有关。
用L2TP-IPSEC道理是一样的，只不过你需要做好抗干扰的准备。

**Comment by wowzql** [comment]
两个服务端对接还是用了 shadowvpn 但是 客户机连接中转部分使用L2TP-IPSEC 时 开启网页缓慢，发现是MTU值的问题 在window端和中间服务器端将 L2TP网卡MTU 值设置成 1500（默认1400） 找了几个人测试， 有的人网页秒开 有的网页打不开要改回1400  难道只能用OPENVPN么。。。技术小白 自己研究了好久。。。求大神指点

**Comment by littlewolf9527** [comment]
l2tp不要改mtu，转发服务器上打开tcp-mss-clamping
还有就是l2tp是udp的协议，很容易就被isp干扰的，限流什么的也是家常便饭
