### ISSUE TITLE
您好 想请教一下关于服务器对接和MTU配置的一些问题

### ISSUE THREAD

**Issue by wowzql** [OkamiSupport/How-to-build-your-own-private-network#3]

**Comment by littlewolf9527** [comment]
TCPMSS请设置为auto clamping，各种网络下的值不一样，交给Kernel来搞定是最好的 :P
你的这个拓扑我现在一直都在用，没什么问题。而且普通的ping和MTU也没什么关系的。
（我的是普通的以太广播网，MTU 1500，VPN的mtu没有设置，mss clamping直接是clamp to pmtu ）
也许应该考虑下提供商超售的问题？
